version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: sudo pip install -q -e .[test]
      - run: cd frontend && yarn install
      - run: pytest --cov=yawn --junitxml=$CIRCLE_TEST_REPORTS/pytest.xml yawn
      - run: flake8 yawn
      - run: cd frontend && env JEST_JUNIT_OUTPUT=$CIRCLE_TEST_REPORTS/jest.xml
          yarn test -- --coverage --testResultsProcessor jest-junit --runInBand
      # build, although it doesn't go anywhere:
      - run: cd frontend/ && yarn build
      - run: ./setup.py sdist
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: dependencies
          paths:
            - frontend/node_modules
