version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-node-browsers
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-{{ checksum "frontend/yarn.lock" }}-{{ checksum "setup.py" }}
            - v2-{{ checksum "frontend/yarn.lock" }}
            - v2
      - run: python -m venv pyenv && source pyenv/bin/activate && pip install -e .[test]
      - run: cd frontend && yarn install
      - save_cache:
          key: v2-{{ checksum "frontend/yarn.lock" }}-{{ checksum "setup.py" }}
          paths:
            - frontend/node_modules
            - pyenv
      - run:
          name: pytest yawn
          command: mkdir reports && source pyenv/bin/activate &&
            pytest --cov=yawn --junitxml=reports/pytest.xml yawn
      - run: source pyenv/bin/activate && flake8 yawn
      - run:
          name: yarn test
          command: cd frontend && env JEST_JUNIT_OUTPUT=../reports/jest.xml
            yarn test -- --coverage --testResultsProcessor jest-junit --runInBand
      # check that building works:
      - run: cd frontend && yarn build
      - run: source pyenv/bin/activate && ./setup.py sdist
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: dist/
