version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-node-browsers
      - image: circleci/postgres:9.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: sudo pip install -e .[test]
      - run: cd frontend && yarn install
      - run:
          name: pytest yawn
          command: mkdir reports &&
            pytest --cov=yawn --junitxml=reports/pytest.xml yawn
      - run: flake8 yawn
      - run:
          name: yarn test
          command: cd frontend && env JEST_JUNIT_OUTPUT=../reports/jest.xml
            yarn test -- --coverage --testResultsProcessor jest-junit --runInBand
      # check that building works:
      - run: cd frontend/ && yarn build
      - run: ./setup.py sdist
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: dependencies
          paths:
            - frontend/node_modules
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: dist/
