# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 05:12
from __future__ import unicode_literals

from django.db import migrations


def create_default_queue(apps, schema_editor):
    Queue = apps.get_model("yawn", "Queue")
    Queue.objects.create(name='default')


class Migration(migrations.Migration):

    dependencies = [
        ('yawn', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_queue),
    ]
